export const LOGIN_URL= "/login"
export const EVENT_URL= "/event"
export const CONFIRMATION_URL= "/confirmation"
export const POST_EVENT_URL= "/postevent"
export const LOGIN_FAILED_URL= "/loginfailed"
export const ALREADY_REGISTERED= "/user_registered"
export const LOST_PASSWORD_URL= "/lostpassword"
export const AGENDA_URL= "/agenda"